#!/bin/sh
echo '{"daily":[{"input":0,"output":0,"cacheRead":0,"cacheWrite":0,"totalTokens":0,"totalCost":3.10,"inputCost":0,"outputCost":0,"cacheReadCost":0,"cacheWriteCost":0}],"missingCostEntries":0}'
